service: backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  hello:
    handler: handler.index
    events:
      - httpApi:
          path: /words
          method: get
